### ISSUE TITLE
Git repository missing: local path in application.properties file of config-server module

### ISSUE THREAD

**Issue by hamedmirzaei** [alirezakhtm/spring-cloud-demo#1]
There is some local path settings in your **application.properties** file of **config-server** module. It corresponds to some git module on your local machine which is not committed. Please resolve the issue.

**Comment by alirezakhtm** [comment]
**ReadMe.md** file updated, all required properties files included in _configfiles_ directory.


Thanks for your feedback. 



----------------------------------------------
For global config module you must copy all files in ```configfiles``` into your desired directory and change the
 ```config-server/src/main/resources/application.properties``` as follow:
 
 ```
 spring.cloud.config.server.git.uri=<your-desired-directory>
 ```
 
 initialize a git repository on this directory
 
 ```
 $ cd <your-desired-directory>
 $ git init
 $ git add --all
 $ git commit -m "initial commit"
 ```

**Comment by hamedmirzaei** [comment]
Thanks, that worked.
